### ISSUE TITLE
u、z和s的fuse方法

### ISSUE THREAD

**Issue by ShaoQiBNU** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#1]
请教一下作者，在对节点的u、z和s向量进行fuse的时候采用了GRU，这几个向量是如何拼接输入GRU的，seq_length是什么，这几个向量的顺序是如何跟nlp的sentence对应的？

**Comment by ethanmock** [comment]
我们采用了GRU作为fuse三种信息的方法，输入为一个 [u, s, z] 的sequence。可以理解为NLP中的一个输入的sentence包含了三个tokens。

**Comment by ShaoQiBNU** [comment]
感谢作者的回复~
我想确认一下：
GRU的输入是一个节点的 [u, s, z](三个tokens作为一个sentence，seq_length=3)？不同节点相当于多个sentence，一起并行执行GRU？

[u, s, z]这3个变量的顺序是否有要求，可否调换？

**Comment by ethanmock** [comment]
您好，
是的，每个节点的[u, s, z]都相当于一个sentence。我们工作没考虑三者的顺序关系，所以顺序没有要求，只要都保持一致就行。

**Comment by ShaoQiBNU** [comment]
谢谢~
