### ISSUE TITLE
some questions about Taobao

### ISSUE THREAD

**Issue by Amelia0312** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#10]
I have to questions:
1.Taobao is a dataset for CTR ,how to get itemID? Do you take the adventure's id as itemID?
2.How to obtain attributes of users and items In Taobao dataset?

**Comment by ethanmock** [comment]
Hi,

1. We treat each advertisement as an item, so the item ID is the advertisement ID.
2. The Taobao dataset contains user and advertisement attributes. You can refer to its metadata for detailed information at https://tianchi.aliyun.com/dataset/dataDetail?dataId=56&lang=en-us#1
