### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by Jhy1993** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#3]
如图
<img width="912" alt="image" src="https://user-images.githubusercontent.com/12387434/126861506-91740e5f-d9c5-4848-9ef3-a03d0e24154e.png">

**Comment by xf8306** [comment]
请问这个问题您解决了吗，我也遇到了相同的问题

> 如图
> <img alt="image" width="912" src="https://user-images.githubusercontent.com/12387434/126861506-91740e5f-d9c5-4848-9ef3-a03d0e24154e.png">

**Comment by ethanmock** [comment]
> 如图
> <img alt="image" width="912" src="https://user-images.githubusercontent.com/12387434/126861506-91740e5f-d9c5-4848-9ef3-a03d0e24154e.png">

你好，这个问题我这里无法复现。报错位置不在提供的代码中，而是在torch_geometric包内部，可能原因是没有正确安装对应的torch或者torch_geometric版本。
