### ISSUE TITLE
Dataset in JSON format

### ISSUE THREAD

**Issue by geo47** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#4]
Hi,

can you please provide the picked dictionary dataset as a text or JSON file?

Thanks

**Comment by ethanmock** [comment]
Hi, 

The current format is a more space-efficient way to store the datasets.

The provided .pkl files can be easily loaded into python dictionary objects by the ```pickle``` package.
Then you can transform them into text or JSON files using corresponding packages.

**Comment by geo47** [comment]
Hi @suyixin12123,

Thanks for the reply.

I understand the reason why we store data in pickled format. I was actually curious about the data fields and format of the files.

Could you please elaborate on the data fields you used in the project and are stored in the pickle files with their description?

Thanks.

**Comment by ethanmock** [comment]
Hi,

Thanks for the suggestion and we may add a file describing the field we used in future updating.
 
Also, you can check the ```feature_dict.pkl``` file that contains all the features we used in a dictionary format: ```feature_name:id```, but they are not categorized by fields.
