### ISSUE TITLE
outer_edge_index

### ISSUE THREAD

**Issue by cs1439071609** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#6]
您好，outer_edge_index是不是存在问题？

**Comment by ethanmock** [comment]
您好，请问您具体指的是什么问题呢？

**Comment by cs1439071609** [comment]
`return Data(x=x, edge_index=edge_index_inner, edge_attr=torch.transpose(edge_index_outer, 0, 1), y=rating)。`
这一部分在进行批处理后模型中得到的outer_edge_index并没有增加索引，每组用户项目交叉交互的索引仍是从0开始，还是原来的索引数。

**Comment by ethanmock** [comment]
> `return Data(x=x, edge_index=edge_index_inner, edge_attr=torch.transpose(edge_index_outer, 0, 1), y=rating)。` 这一部分在进行批处理后模型中得到的outer_edge_index并没有增加索引，每组用户项目交叉交互的索引仍是从0开始，还是原来的索引数。

这里的不论inner还是outer的索引都对应user_list + item_list这一个list，即前一半索引[0:u_n]对应的是user的attributes，后一半的索引[u_n:]对应的是item的attributes。
Inner interaction对应的索引对只在user的attribute之间或者item的attribute之间，即如果一个interaction的第一个值的索引在[0:u_n]，第二个索引一定也在[0:u_n]。
outer interaction对应的索引对如果一个在[0:u_n]之间，另一个一定在[u_n:]之间。

**Comment by cs1439071609** [comment]
如果batch_size为2。
第1组数据用户有3个属性，项目有2个属性。outer_edge_index为[[0,0,1,1,2,2,3,3,3,4,4,4],[3,4,3,4,3,4,0,1,2,0,1,2]]。
第2组数据用户有3个属性，项目有3个属性。outer_edge_index为[[0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],[3,4,5,3,4,5,3,4,5,0,1,2,0,1,2,0,1,2]]
经过批处理后模型中应该得到[[0,0,1,1,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,……],[3,4,3,4,3,4,0,1,2,0,1,2,8,9,10,8,9,10,8,9,10]]
但是此时得到的是[[0,0,1,1,2,2,3,3,3,4,4,4,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],[3,4,3,4,3,4,0,1,2,0,1,2,3,4,5,3,4,5,3,4,5,0,1,2,0,1,2,0,1,2]]。
我是这样认为，可能是我理解有误。

**Comment by ethanmock** [comment]
> 如果batch_size为2。 第1组数据用户有3个属性，项目有2个属性。outer_edge_index为[[0,0,1,1,2,2,3,3,3,4,4,4],[3,4,3,4,3,4,0,1,2,0,1,2]]。 第2组数据用户有3个属性，项目有3个属性。outer_edge_index为[[0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],[3,4,5,3,4,5,3,4,5,0,1,2,0,1,2,0,1,2]] 经过批处理后模型中应该得到[[0,0,1,1,2,2,3,3,3,4,4,4,5,5,5,6,6,6,7,7,7,……],[3,4,3,4,3,4,0,1,2,0,1,2,8,9,10,8,9,10,8,9,10]] 但是此时得到的是[[0,0,1,1,2,2,3,3,3,4,4,4,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],[3,4,3,4,3,4,0,1,2,0,1,2,3,4,5,3,4,5,3,4,5,0,1,2,0,1,2,0,1,2]]。 我是这样认为，可能是我理解有误。

这里的索引流程是每个Data中的edge index对应的是该Data传入的user_list + item_list的下标（[0:len(user_list + item_list)]），而user_list + item_list的每个元素储存了对应attribute在整个数据集里的唯一id。通过下表获取user_list + item_list里的值来得到attribute的id。

这是参考了torch_geometric存储graph的标准。比较详细的例子可以查看torch_geometric.data和torch_geometric的教程。

**Comment by cs1439071609** [comment]
还是上边的数据，模型中得到的inner_edge_index是[[0,0,0,1,1,1,2,2,2,3,3,4,4,5,5,5,6,6,6,7,7,7,8,8,8,……],[0,1,2,0,1,2,0,1,2,3,4,3,4,5,6,7,5,6,7,5,6,7,8,9,10,……]]
得到的outer_edge_index为[[0,0,1,1,2,2,3,3,3,4,4,4,0,0,0,1,1,1,2,2,2,3,3,3,4,4,4,5,5,5],[3,4,3,4,3,4,0,1,2,0,1,2,3,4,5,3,4,5,3,4,5,0,1,2,0,1,2,0,1,2]]
