### ISSUE TITLE
直接运行报 Assertion `srcIndex < srcSelectDimSize` failed 错误

### ISSUE THREAD

**Issue by agedcat** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#8]
![image](https://user-images.githubusercontent.com/76728773/146322547-0b10509e-3ce3-462d-99a7-f17924811412.png)
直接运行  python main.py --dataset=book-crossing --num_user_features=3 --dim=64 --hidden_layer=256 --batch_size=1 命令报错
能请教下是什么原因么？

**Comment by ethanmock** [comment]
您好，这个问题目前我们这里暂时无法复现，具体原因还在寻找中。猜测可能是因为没有正确安装对应的torch和torch_geometric版本导致的。

**Comment by agedcat** [comment]
这边定位的问题在pyg的message_passing.py中，能麻烦您那边追踪下原因么？个人猜测是pyg版本的问题，这边用的pyg是最新版本，2.0.2，以供参考。

**Comment by ethanmock** [comment]
Bug fixed.
