### ISSUE TITLE
Why should some features of the item be considered as multiple attributes?

### ISSUE THREAD

**Issue by He-Yichen** [ruizhang-ai/GMCF_Neural_Graph_Matching_based_Collaborative_Filtering#9]
Such as in the item_dict of the book-crossing, why each word of "Book-Title" is considered as an attribute?
For eaxmple the Book-Title of item 0002005018 is “Clara Callan”，why "Clara" is considered as an attribute, and "Callan" is also considered as an attribute? Why not “Clara Callan” is considered as an attribute? 
My English is not very good, looking forward to your reply，thank you! @ruizhang-ai @ethanmock 
Could you share more details about generating a PKL file?
您好，我的英文不太好，下面是中文阐述我的疑问：
我想请问一下为什么要把物品的一些特征里面的内容拆分成几个属性？例如Book-crossing，有一个Item(0002005018)，它的Book-Title是“Clara Callan”，为什么它的Book-Title里面的每一个单词都要拆分成一个属性添加到item_dict里，而不是把整个Book-Title的内容（“Clara Callan”）作为物品的一个属性呢？
请问您能分享一下如何产生PKL数据文件的细节吗？

**Comment by ethanmock** [comment]
你好，拆分成不同的属性是为了增加item之间的关联程度，让不同的item之间能够依靠属性关联起来，通过这种方法利用属性信息更好的学习物品（用户）之间的collaborative的信息（比如两本书都有同一个单词，可能这两本书有一部分相似性）。如果把整个title看成一个属性，title属性在item之间没有重叠（假设所有的书名字都不同），和ID属性无差别。

这个工作主要关注的不是NLP的处理，所以我们没有用很复杂的NLP方法处理title（如NER等），只对每个单词做了标准的处理（如Tokenization， stop words removal, stemming, lemmatization等）。

PKL的文件格式在readme文件中可以找到，都为python dictionary格式。三个文件的关联为：feature_dict中的key是每个属性（包括物品和用户ID）的描述，value是对应在模型中的embedding id。item_dict和user_dict中的key各自对应的是rating file中的user和item的id，他们的value中的id和feature_dict中的value是一致的。

**Comment by He-Yichen** [comment]
明白了，谢谢作者！
